import { LevelTheme, Language } from './types';

export const MAP_WIDTH = 45; 
export const MAP_HEIGHT = 25;
export const MAX_LEVELS = 150;

export const INITIAL_PLAYER_STATS = {
  hp: 120,
  maxHp: 120,
  attack: 12,
  armor: 8,
  maxArmor: 8,
  speed: 12,
};

export const THEME_CONFIG: Record<LevelTheme, { nameKey: string, wall: string, floor: string, char: string, wallChar: string }> = {
  FOREST: { nameKey: 'theme_forest', wall: 'text-green-800', floor: 'text-green-950', char: '♣', wallChar: 'T' },
  DESERT: { nameKey: 'theme_desert', wall: 'text-orange-700', floor: 'text-yellow-900', char: '≈', wallChar: '▒' },
  SNOW: { nameKey: 'theme_snow', wall: 'text-cyan-100', floor: 'text-blue-900', char: '·', wallChar: '❄' },
  CAVE: { nameKey: 'theme_cave', wall: 'text-zinc-600', floor: 'text-zinc-900', char: '°', wallChar: '▓' },
  MATRIX: { nameKey: 'theme_matrix', wall: 'text-emerald-500', floor: 'text-black', char: '1', wallChar: '0' },
  INFERNO: { nameKey: 'theme_inferno', wall: 'text-red-600', floor: 'text-red-950', char: '″', wallChar: '▲' },
  VOID: { nameKey: 'theme_void', wall: 'text-purple-900', floor: 'text-black', char: ' ', wallChar: '?' },
};

export const TILE_COLORS: Record<string, string> = {
  WALL: 'text-zinc-700',
  FLOOR: 'text-zinc-900',
  PLAYER: 'text-yellow-400',
  ENEMY: 'text-red-500',
  CHEST: 'text-blue-400',
  STAIRS: 'text-green-500',
  KEY: 'text-yellow-500',
  POTION: 'text-pink-400',
  ITEM: 'text-purple-400',
  MERCHANT: 'text-indigo-400',
  TRON: 'text-cyan-400',
  PET: 'text-orange-400'
};

export const ENEMY_TYPES = [
  { name: 'Rastejante', minLevel: 1 },
  { name: 'Vigia Escuro', minLevel: 1 },
  { name: 'Guerreiro Caído', minLevel: 3 },
  { name: 'Espectro', minLevel: 5 },
  { name: 'Bruto de Elite', minLevel: 8 },
  { name: 'Assassino das Sombras', minLevel: 10 },
  { name: 'Colosso Arcano', minLevel: 12 },
  { name: 'Soberano do Abismo', minLevel: 14 },
];

export const ITEM_POOL = [
  { name: 'Daga Curva', stat: 'attack', value: 5, iconType: 'sword', basePrice: 20 },
  { name: 'Couraça Reforçada', stat: 'maxArmor', value: 4, iconType: 'shield', basePrice: 18 },
  { name: 'Botas de Mercúrio', stat: 'speed', value: 6, iconType: 'boot', basePrice: 25 },
  { name: 'Amuleto de Sangue', stat: 'maxHp', value: 30, iconType: 'heart', basePrice: 40 },
  { name: 'Espada de Ébano', stat: 'attack', value: 12, iconType: 'sword', basePrice: 60 },
  { name: 'Capa das Sombras', stat: 'speed', value: 10, iconType: 'boot', basePrice: 50 },
  { name: 'Manto de Ferro', stat: 'maxArmor', value: 8, iconType: 'shield', basePrice: 55 },
  { name: 'Essência Vital', stat: 'maxHp', value: 50, iconType: 'heart', basePrice: 80 },
];

export const TRANSLATIONS: Record<Language, any> = {
  PT: {
    hero_placeholder: "NOME DO HERÓI",
    continue_journey: "Continuar Jornada",
    new_game: "Novo Jogo",
    start_journey: "Iniciar Jornada",
    feedback: "Feedback",
    abyss: "O Abismo Infinito",
    depth: "Profundidade",
    level: "Nível",
    hp: "VIDA",
    armor: "ESCUDO",
    atk: "ATK",
    vel: "VEL",
    diary: "Diário",
    view_diary: "Ver Diário",
    hide_diary: "Ocultar Diário",
    death_title: "MORTE",
    death_desc: "O Abismo reivindicou sua alma.",
    rebirth: "Renascer",
    victory: "Vitória",
    collect_reward: "COLETAR RECOMPENSA",
    succumb: "SUCUMBIR AO ABISMO",
    chest_title: "Bênção do Baú",
    merchant_title: "Mercador Errante",
    close_deal: "Fechar Negócio",
    bought_pet: "Mascote comprado!",
    bought_potion: "Poção comprada!",
    bought_item: "Equipado!",
    tron_active: "CAVALO FANTASMA ATIVADO!",
    language_br: "Português",
    language_us: "English",
    language_es: "Español",
    theme_forest: 'Floresta Sombria',
    theme_desert: 'Dunas de Sangue',
    theme_snow: 'Pico Congelado',
    theme_cave: 'Gruta Profunda',
    theme_matrix: 'Terminal Matrix',
    theme_inferno: 'Abismo Infernal',
    theme_void: 'O Vazio',
    final_stats: "ESTATÍSTICAS FINAIS",
    blood: "SANGUE",
    key: "CHAVE",
    combat_dealt: "causou",
    combat_damage: "de dano",
    combat_absorbed: "absorveu",
    combat_player: "Você",
    combat_enemy: "Inimigo",
    combat_pet: "Mascote",
    pet_lobo: "LOBO",
    pet_puma: "PUMA",
    pet_coruja: "CORUJA",
    pet_cavalo: "CAVALO",
    buy_horse: "ALUGAR CAVALO",
    descending: "Descendo para o nível",
    log_entry: "entrou no abismo.",
    log_depth: "Alcançou a profundidade",
    log_key: "Chave coletada!",
    log_locked: "Trancado. Precisa de Chave e Sangue!",
    log_trampled: "Atropelado!",
    next: "PRÓXIMO",
    start: "COMEÇAR"
  },
  EN: {
    hero_placeholder: "HERO NAME",
    continue_journey: "Continue Journey",
    new_game: "New Game",
    start_journey: "Start Journey",
    feedback: "Feedback",
    abyss: "The Infinite Abyss",
    depth: "Depth",
    level: "Level",
    hp: "HP",
    armor: "ARMOR",
    atk: "ATK",
    vel: "SPD",
    diary: "Log",
    view_diary: "View Log",
    hide_diary: "Hide Log",
    death_title: "DEATH",
    death_desc: "The Abyss claimed your soul.",
    rebirth: "Rebirth",
    victory: "Victory",
    collect_reward: "COLLECT REWARD",
    succumb: "SUCCUMB TO THE ABYSS",
    chest_title: "Chest Blessing",
    merchant_title: "Wandering Merchant",
    close_deal: "Close Deal",
    bought_pet: "Pet bought!",
    bought_potion: "Potion bought!",
    bought_item: "Equipped!",
    tron_active: "GHOST HORSE ACTIVATED!",
    language_br: "Portuguese",
    language_us: "English",
    language_es: "Spanish",
    theme_forest: 'Dark Forest',
    theme_desert: 'Blood Dunes',
    theme_snow: 'Frozen Peak',
    theme_cave: 'Deep Grotto',
    theme_matrix: 'Terminal Matrix',
    theme_inferno: 'Infernal Abyss',
    theme_void: 'The Void',
    final_stats: "FINAL STATS",
    blood: "BLOOD",
    key: "KEY",
    combat_dealt: "dealt",
    combat_damage: "damage",
    combat_absorbed: "absorbed",
    combat_player: "You",
    combat_enemy: "Enemy",
    combat_pet: "Pet",
    pet_lobo: "WOLF",
    pet_puma: "PUMA",
    pet_coruja: "OWL",
    pet_cavalo: "HORSE",
    buy_horse: "RENT HORSE",
    descending: "Descending to level",
    log_entry: "entered the abyss.",
    log_depth: "Reached depth",
    log_key: "Key collected!",
    log_locked: "Locked. Need Key & Blood!",
    log_trampled: "Trampled!",
    next: "NEXT",
    start: "START"
  },
  ES: {
    hero_placeholder: "NOMBRE DEL HÉROE",
    continue_journey: "Continuar Jornada",
    new_game: "Nuevo Juego",
    start_journey: "Iniciar Jornada",
    feedback: "Feedback",
    abyss: "El Abismo Infinito",
    depth: "Profundidad",
    level: "Nivel",
    hp: "VIDA",
    armor: "ESCUDO",
    atk: "ATK",
    vel: "VEL",
    diary: "Diario",
    view_diary: "Ver Diario",
    hide_diary: "Ocultar Diario",
    death_title: "MUERTE",
    death_desc: "El Abismo reclamó tu alma.",
    rebirth: "Renacer",
    victory: "Victoria",
    collect_reward: "COBRAR RECOMPENSA",
    succumb: "SUCUMBIR AL ABISMO",
    chest_title: "Bendición del Cofre",
    merchant_title: "Mercader Errante",
    close_deal: "Cerrar Trato",
    bought_pet: "¡Mascota comprada!",
    bought_potion: "¡Poción comprada!",
    bought_item: "¡Equipado!",
    tron_active: "¡CABALLO FANTASMA ACTIVADO!",
    language_br: "Portugués",
    language_us: "Inglés",
    language_es: "Español",
    theme_forest: 'Bosque Sombrío',
    theme_desert: 'Dunas de Sangre',
    theme_snow: 'Pico Congelado',
    theme_cave: 'Gruta Profunda',
    theme_matrix: 'Terminal Matrix',
    theme_inferno: 'Abismo Infernal',
    theme_void: 'El Vacío',
    final_stats: "ESTADÍSTICAS FINALES",
    blood: "SANGRE",
    key: "LLAVE",
    combat_dealt: "causó",
    combat_damage: "de daño",
    combat_absorbed: "absorbió",
    combat_player: "Tú",
    combat_enemy: "Enemigo",
    combat_pet: "Mascota",
    pet_lobo: "LOBO",
    pet_puma: "PUMA",
    pet_coruja: "BÚHO",
    pet_cavalo: "CABALLO",
    buy_horse: "ALQUILAR CABALLO",
    descending: "Descendiendo al nivel",
    log_entry: "entró en el abismo.",
    log_depth: "Alcanzó la profundidad",
    log_key: "¡Llave recolectada!",
    log_locked: "¡Cerrado. Necesitas Llave y Sangre!",
    log_trampled: "¡Atropellado!",
    next: "SIGUIENTE",
    start: "EMPEZAR"
  }
};