
import { LevelTheme, Language, Relic, AltarEffect } from './types';

export const MAP_WIDTH = 100;
export const MAP_HEIGHT = 60;
export const MAX_LEVELS = 150;

export const INITIAL_PLAYER_STATS = {
  hp: 120,
  maxHp: 120,
  attack: 12,
  armor: 8,
  maxArmor: 8,
  speed: 12,
};

export const POISONOUS_ENEMIES = [
  'Aranha Cavernosa', 
  'Escorpião Gigante', 
  'Verme da Areia', 
  'Serpente Aquática', 
  'Bruxa da Floresta', 
  'Mutante Corrompido',
  'Lodo Venenoso', // Novo
  'Aberração Putrefata', // Novo
  'Sanguessuga Gigante' // Novo
];

export const RELICS_POOL: Relic[] = [
  { id: 'slots', name: 'Bolsa Expandida', description: '+5 slots no inventário.', icon: 'Backpack' },
  { id: 'bleed', name: 'Dente Serrilhado', description: '+5% de chance permanente de causar sangramento.', icon: 'Droplets' },
  { id: 'defense', name: 'Placa Rachada', description: 'Reduz em 10 o dano recebido (mínimo de 1).', icon: 'ShieldAlert' },
  { id: 'crit', name: 'Olho do Caçador', description: '+5% de acerto crítico.', icon: 'Eye' },
  { id: 'power', name: 'Punho Enrijecido', description: 'O primeiro ataque em cada andar causa +10% de dano.', icon: 'Zap' },
  { id: 'vamp', name: 'Ampulheta Carmesim', description: 'Recupera 15% de vida ao matar um inimigo (limite por andar).', icon: 'Hourglass' },
  { id: 'alch', name: 'Resíduo Alquímico', description: 'Poções curam +5% a mais.', icon: 'FlaskConical' },
  { id: 'save', name: 'Frasco Instável', description: '5% de chance de uma poção não ser consumida ao usar.', icon: 'RefreshCcw' },
  { id: 'memory', name: 'Memória Destilada', description: 'A primeira poção usada em cada run tem efeito dobrado.', icon: 'Brain' },
  { id: 'gaze', name: 'Gaze Antiga', description: 'Sempre começa a run com 1 poção que cura 75% da vida.', icon: 'Sparkles' },
  { id: 'collar', name: 'Coleira de Ossos', description: 'Pets causam +10 de dano base.', icon: 'Skull' },
  { id: 'bag', name: 'Bolsa Costurada', description: '+5% de ouro ganho.', icon: 'Coins' },
  { id: 'coin', name: 'Moeda Antiga', description: '5% de chance de inimigos droparem ouro extra.', icon: 'CircleDollarSign' },
  { id: 'heart', name: 'Coração Fissurado', description: '+10% dano, -5% HP máximo.', icon: 'HeartOff' },
  { id: 'mark', name: 'Marca do Sacrifício', description: 'Começa a run com -10% vida, mas inicia com +60 moedas.', icon: 'Flame' },
  { id: 'echo', name: 'Eco das Mortes', description: '20% de todos os atributos do personagem anterior são herdados.', icon: 'Ghost' },
  { id: 'life_long', name: 'Vida Longa', description: '+30 de vida máxima.', icon: 'Heart' },
];

export const BLESSINGS_POOL: AltarEffect[] = [
  { id: 'sharp_blood', type: 'BLESSING', nameKey: 'b_sharp_name', descKey: 'b_sharp_desc' },
  { id: 'contained_fury', type: 'BLESSING', nameKey: 'b_fury_name', descKey: 'b_fury_desc' },
  { id: 'anxious_strike', type: 'BLESSING', nameKey: 'b_strike_name', descKey: 'b_strike_desc' },
  { id: 'consecrated_fists', type: 'BLESSING', nameKey: 'b_fists_name', descKey: 'b_fists_desc' },
  { id: 'open_eyes', type: 'BLESSING', nameKey: 'b_eyes_name', descKey: 'b_eyes_desc' },
  { id: 'pilgrim_luck', type: 'BLESSING', nameKey: 'b_luck_name', descKey: 'b_luck_desc' },
  { id: 'surrendered_blood', type: 'BLESSING', nameKey: 'b_surrendered_name', descKey: 'b_surrendered_desc' },
  { id: 'accepted_offering', type: 'BLESSING', nameKey: 'b_accepted_name', descKey: 'b_accepted_desc' },
  { id: 'sacred_greed', type: 'BLESSING', nameKey: 'b_greed_name', descKey: 'b_greed_desc' },
  { id: 'merchant_blessing', type: 'BLESSING', nameKey: 'b_merchant_name', descKey: 'b_merchant_desc' },
  { id: 'consecrated_chest', type: 'BLESSING', nameKey: 'b_chest_name', descKey: 'b_chest_desc' },
];

export const CURSES_POOL: AltarEffect[] = [
  { id: 'fragile_blood', type: 'CURSE', nameKey: 'c_fragile_name', descKey: 'c_fragile_desc' },
  { id: 'trembling_hands', type: 'CURSE', nameKey: 'c_hands_name', descKey: 'c_hands_desc' },
  { id: 'short_breath', type: 'CURSE', nameKey: 'c_breath_name', descKey: 'c_breath_desc' },
  { id: 'mark_of_prey', type: 'CURSE', nameKey: 'c_mark_name', descKey: 'c_mark_desc' },
  { id: 'slow_reflexes', type: 'CURSE', nameKey: 'c_reflexes_name', descKey: 'c_reflexes_desc' },
  { id: 'ritual_darkness', type: 'CURSE', nameKey: 'c_darkness_name', descKey: 'c_darkness_desc' },
  { id: 'profane_thirst', type: 'CURSE', nameKey: 'c_thirst_name', descKey: 'c_thirst_desc' },
  { id: 'denied_offering', type: 'CURSE', nameKey: 'c_denied_name', descKey: 'c_denied_desc' },
  { id: 'cursed_greed', type: 'CURSE', nameKey: 'c_greed_name', descKey: 'c_greed_desc' },
  { id: 'less_weight', type: 'CURSE', nameKey: 'c_weight_name', descKey: 'c_weight_desc' },
  { id: 'blood_tribute', type: 'CURSE', nameKey: 'c_tribute_name', descKey: 'c_tribute_desc' },
];

export const BIOME_ENEMIES: Record<LevelTheme, string[]> = {
  CAVE: ['Morcego Gigante', 'Aranha Cavernosa', 'Goblin', 'Verme de Pedra', 'Troll'],
  SNOW: ['Lobo de Gelo', 'Elemental Congelado', 'Guerreiro Nórdico Espectral', 'Golem de Gelo', 'Espírito da Nevassa'],
  DESERT: ['Escorpião Gigante', 'Verme da Areia', 'Bandido do Deserto', 'Esqueleto Soterrado', 'Djinn Corrompido'],
  FOREST: ['Lobo Selvagem', 'Ent Corrompido', 'Arqueiro Espectral', 'Besta da Mata', 'Bruxa da Floresta'],
  INFERNO: ['Demônio Menor', 'Ímpio Flamejante', 'Cavaleiro Infernal', 'Cão do Inferno', 'Sacerdote Demoníaco'],
  RUINS: ['Guardião de Pedra', 'Esqueleto Ancestral', 'Autômato Antigo', 'Cultista Esquecido', 'Espírito das Ruínas'],
  VOID: ['Criatura Sombria', 'Aberração sem Forma', 'Sombra Viva', 'Observador do Vazio', 'Entidade Faminta'],
  MECHANICAL: ['Autômato de Combate', 'Drone Defeituoso', 'Torre Mecânica', 'Engrenagem Viva', 'Sentinela de Aço'],
  CORRUPTED: ['Mutante Corrompido', 'Besta Deformada', 'Humano Possuído', 'Parasita Gigante', 'Massa Orgânica Hostil'],
  CATACOMBS: ['Zumbi Encharcado', 'Criatura Anfíbia', 'Serpente Aquática', 'Espírito Afogado', 'Slime Aquático'],
  OSSUARY: ['Esqueleto Armado', 'Necromante', 'Guardião de Ossos', 'Espírito Funerário', 'Colosso Ósseo'],
  ASTRAL: ['Entidade Etérea', 'Guardião Astral', 'Fragmento de Consciência', 'Eco Vivo', 'Seres Translúcidos'],
  MATRIX: ['Programa Corrompido', 'Agente de Segurança', 'Vírus Consciente', 'Avatar Hostil', 'Entidade Digital'],
  FURNACE: ['Íncubo de Cinzas', 'Larva Ígnea', 'Guardião da Brasa', 'Súcubo Incandescente', 'Elemental de Fogo Instável', 'Colosso Vulcânico'],
  SWAMP: ['Lodo Venenoso', 'Sanguessuga Gigante', 'Morcego Doente', 'Xamã do Brejo', 'Crocodilo Mutante', 'Aberração Putrefata'],
  TEMPLE: ['Estátua Animada', 'Sentinela Antiga', 'Sacerdote Profanado', 'Autômato Rúnico', 'Guardião de Obelisco', 'Avatar do Templo'],
  CHAOS: ['Entidade Fraturada', 'Eco Distorcido', 'Parasita do Caos', 'Aberração Mutável', 'Vulto Caótico', 'Núcleo Anômalo'],
  HIVE: ['Larva Rasteira', 'Operária da Colmeia', 'Soldado Quitinoso', 'Aranha Tecelã', 'Rainha Menor', 'Matriz da Colmeia'],
};

export const THEME_CONFIG: Record<LevelTheme, { nameKey: string, wall: string, floor: string, char: string, wallChar: string }> = {
  CAVE: { nameKey: 'theme_cave', wall: 'text-zinc-600', floor: 'text-zinc-900', char: '°', wallChar: '▓' },
  SNOW: { nameKey: 'theme_snow', wall: 'text-cyan-100', floor: 'text-blue-900', char: '·', wallChar: '❄' },
  DESERT: { nameKey: 'theme_desert', wall: 'text-orange-700', floor: 'text-yellow-900', char: '≈', wallChar: '▒' },
  FOREST: { nameKey: 'theme_forest', wall: 'text-green-800', floor: 'text-green-950', char: '♣', wallChar: 'T' },
  INFERNO: { nameKey: 'theme_inferno', wall: 'text-red-600', floor: 'text-red-950', char: '″', wallChar: '▲' },
  RUINS: { nameKey: 'theme_ruins', wall: 'text-amber-800', floor: 'text-stone-900', char: '☖', wallChar: '🧱' },
  VOID: { nameKey: 'theme_void', wall: 'text-purple-900', floor: 'text-black', char: ' ', wallChar: '?' },
  MECHANICAL: { nameKey: 'theme_mechanical', wall: 'text-zinc-400', floor: 'text-zinc-800', char: '⚙', wallChar: '█' },
  CORRUPTED: { nameKey: 'theme_corrupted', wall: 'text-fuchsia-900', floor: 'text-purple-950', char: '☣', wallChar: '✕' },
  CATACOMBS: { nameKey: 'theme_catacombs', wall: 'text-slate-700', floor: 'text-slate-900', char: '♒', wallChar: '⛩' },
  OSSUARY: { nameKey: 'theme_ossuary', wall: 'text-zinc-200', floor: 'text-zinc-700', char: '☠', wallChar: '✟' },
  ASTRAL: { nameKey: 'theme_astral', wall: 'text-sky-400', floor: 'text-sky-950', char: '✨', wallChar: '✧' },
  MATRIX: { nameKey: 'theme_matrix', wall: 'text-emerald-500', floor: 'text-black', char: '1', wallChar: '0' },
  FURNACE: { nameKey: 'theme_furnace', wall: 'text-orange-600', floor: 'text-red-950', char: '~', wallChar: '♨' },
  SWAMP: { nameKey: 'theme_swamp', wall: 'text-emerald-700', floor: 'text-green-950', char: '≈', wallChar: '⍾' },
  TEMPLE: { nameKey: 'theme_temple', wall: 'text-amber-500', floor: 'text-stone-900', char: '∏', wallChar: '🏛' },
  CHAOS: { nameKey: 'theme_chaos', wall: 'text-fuchsia-600', floor: 'text-purple-950', char: '?', wallChar: '🌀' },
  HIVE: { nameKey: 'theme_hive', wall: 'text-yellow-700', floor: 'text-orange-950', char: '⬡', wallChar: '🕸' },
};

export const TILE_COLORS: Record<string, string> = {
  WALL: 'text-zinc-700',
  FLOOR: 'text-zinc-900',
  PLAYER: 'text-yellow-400',
  ENEMY: 'text-red-500',
  CHEST: 'text-blue-400',
  STAIRS: 'text-green-500',
  KEY: 'text-yellow-500',
  POTION: 'text-pink-400',
  ITEM: 'text-purple-400',
  MERCHANT: 'text-indigo-400',
  ALTAR: 'text-purple-500',
  TRON: 'text-cyan-400',
  PET: 'text-orange-400',
  TRAP: 'text-zinc-500',
  EGG: 'text-white'
};

export const ENEMY_TYPES = [
  { name: 'Rastejante', minLevel: 1 },
  { name: 'Vigia Escuro', minLevel: 1 },
  { name: 'Guerreiro Caído', minLevel: 3 },
  { name: 'Espectro', minLevel: 5 },
  { name: 'Bruto de Elite', minLevel: 7 },
  { name: 'Assassino das Sombras', minLevel: 10 },
  { name: 'Colosso Arcano', minLevel: 12 },
  { name: 'Soberano do Abismo', minLevel: 14 },
];

export const ITEM_POOL = [
  { name: 'Daga Curva', stat: 'attack', value: 5, iconType: 'sword', basePrice: 22 },
  { name: 'Couraça Reforçada', stat: 'maxArmor', value: 4, iconType: 'shield', basePrice: 18 },
  { name: 'Botas de Mercúrio', stat: 'speed', value: 6, iconType: 'boot', basePrice: 27 },
  { name: 'Amuleto de Sangue', stat: 'maxHp', value: 30, iconType: 'heart', basePrice: 44 },
  { name: 'Espada de Ébano', stat: 'attack', value: 12, iconType: 'sword', basePrice: 66 },
  { name: 'Capa das Sombras', stat: 'speed', value: 10, iconType: 'boot', basePrice: 50 },
  { name: 'Manto de Ferro', stat: 'maxArmor', value: 8, iconType: 'shield', basePrice: 55 },
  { name: 'Essência Vital', stat: 'maxHp', value: 50, iconType: 'heart', basePrice: 80 },
];

export const TRANSLATIONS: Record<Language, any> = {
  PT: {
    inventory_title: "INVENTÁRIO",
    inventory_full: "Inventário cheio!",
    use: "USAR",
    store: "GUARDAR",
    relic_choice: "ESCOLHA UMA RELÍQUIA",
    relic_active: "RELÍQUIA ATIVA",
    hero_placeholder: "NOME DO HERÓI",
    continue_journey: "Continuar Jornada",
    new_game: "Novo Jogo",
    start_journey: "Iniciar Jornada",
    feedback: "Feedback",
    abyss: "O Abismo Infinito",
    depth: "ProfundIDADE",
    level: "Nível",
    hp: "VIDA",
    armor: "ESCUDO",
    atk: "ATK",
    vel: "VEL",
    diary: "Diario",
    view_diary: "Ver Diário",
    hide_diary: "Ocultar Diário",
    death_title: "MORTE",
    death_desc: "O Abismo reivindicou sua alma.",
    rebirth: "Renascer",
    victory: "Vitória",
    collect_reward: "COLETAR RECOMPENSA",
    succumb: "SUCUMBIR AO ABISMO",
    chest_title: "Bênção do Baú",
    merchant_title: "Mercador Errante",
    altar_title: "Altar das Sombras",
    altar_inactive: "O Altar permanece silente. Mate um inimigo primeiro.",
    altar_prompt: "Prostre-se diante do Altar e aceite seu destino.",
    altar_button: "ORAR",
    close_deal: "Fechar Negócio",
    bought_pet: "Mascote comprado!",
    bought_potion: "Poção comprada!",
    bought_item: "Equipado!",
    tron_active: "CAVALO FANTASMA ATIVADO!",
    language_br: "Português",
    language_us: "English",
    language_es: "Español",
    theme_cave: 'Cavernas',
    theme_snow: 'Picos de Gelo',
    theme_desert: 'Dunas',
    theme_forest: 'Floresta',
    theme_inferno: 'Zona Infernal',
    theme_ruins: 'Ruínas Antigas',
    theme_void: 'Abismo',
    theme_mechanical: 'Complexo Mecânico',
    theme_corrupted: 'Zona Corrompida',
    theme_catacombs: 'Catacumbas Alagadas',
    theme_ossuary: 'Ossuário',
    theme_astral: 'Plano Astral',
    theme_matrix: 'Matrix',
    theme_furnace: 'Fornalha Abissal',
    theme_swamp: 'Pântano Tóxico',
    theme_temple: 'Templo Esquecido',
    theme_chaos: 'Zona do Caos',
    theme_hive: 'Colmeia Profunda',
    final_stats: "ESTATÍSTICAS FINAIS",
    blood: "SANGUE",
    key: "CHAVE",
    combat_dealt: "causou",
    combat_damage: "de dano",
    combat_absorbed: "absorveu",
    combat_player: "Você",
    combat_enemy: "Inimigo",
    combat_pet: "Mascote",
    pet_lobo: "LOBO",
    pet_puma: "PUMA",
    pet_corvo: "CORVO",
    pet_cavalo: "CAVALO",
    buy_horse: "ALUGAR CAVALO",
    descending: "Descendo para o nível",
    log_entry: "entrou no abismo.",
    log_depth: "Alcançou a profundidade",
    log_key: "Chave coletada!",
    log_locked: "Trancado. Mate 1 inimigo e pegue a chave!",
    log_trampled: "Atropelado!",
    next: "PRÓXIMO",
    start: "COMEÇAR",
    tutorial_title: "BEM-VINDO AO ABISMO",
    tutorial_guide_title: "Guia de Sobrevivência:",
    tutorial_hp: "VIDA",
    tutorial_hp_desc: "Mantenha acima de 0 ou sua run termina.",
    tutorial_atk: "ATAQUE",
    tutorial_atk_desc: "Dano causado por golpe automático.",
    tutorial_def: "ESCUDO",
    tutorial_def_desc: "Protege sua vida e regenera após cada luta.",
    tutorial_spd: "VELOCIDADE",
    tutorial_spd_desc: "Define quem golpeia primeiro.",
    tutorial_trial_title: "A PROVAÇÃO",
    tutorial_trial_desc: "As escadas estão lacradas. Mate ao menos um inimigo e pegue a chave para avançar.",
    tutorial_btn: "ESTOU PRONTO",
    b_sharp_name: "Sangue Afiado",
    b_sharp_desc: "+10% de dano após a primeira morte neste andar.",
    b_fury_name: "Fúria Contida",
    b_fury_desc: "+15% de dano enquanto estiver com menos de 50% de vida.",
    b_strike_name: "Golpe Ansioso",
    b_strike_desc: "O seu próximo ataque causa dano dobrado.",
    b_fists_name: "Punhos Consagrados",
    b_fists_desc: "Seus ataques ignoram metade da armadura inimiga.",
    b_eyes_name: "Olhos Abertos",
    b_eyes_desc: "A localização da chave foi revelada com pegadas brilhantes.",
    b_luck_name: "Sorte Peregrina",
    b_luck_desc: "Baús extras podem aparecer com 100 moedas de ouro.",
    b_surrendered_name: "Sangue Rendido",
    b_surrendered_desc: "Recupera 30% de vida ao matar inimigos.",
    b_accepted_name: "Oferta Aceita",
    b_accepted_desc: "A próxima poção usada neste andar não será consumida.",
    b_greed_name: "Ganância Sagrada",
    b_greed_desc: "Inimigos dropam mais ouro neste andar.",
    b_merchant_name: "Bênção do Mercador",
    b_merchant_desc: "Itens da loja custam 20% menos até o próximo nível.",
    b_chest_name: "Baú Consagrado",
    b_chest_desc: "O próximo baú concede bônus duplicado.",
    c_fragile_name: "Sangue Frágil",
    c_fragile_desc: "Você recebe +10% de dano de todas as fontes.",
    c_hands_name: "Mãos Trêmulas",
    c_hands_desc: "Você tem 25% de chance de errar seus ataques.",
    c_breath_name: "Fôlego Curto",
    c_breath_desc: "Você não pode atacar em turnos consecutivos.",
    c_mark_name: "Marca da Presa",
    c_mark_desc: "Ataques inimigos aplicam sangramento (-2 HP por turno).",
    c_reflexes_name: "Reflexos Lentos",
    c_reflexes_desc: "Inimigos sempre atacam primeiro no combate.",
    c_darkness_name: "Escuridão Ritual",
    c_darkness_desc: "Campo de visão reduzido drasticamente.",
    c_thirst_name: "Sede Profana",
    c_thirst_desc: "Poções de cura recuperam 10% a menos de vida.",
    c_denied_name: "Oferta Negada",
    c_denied_desc: "A próxima poção usada será consumida sem efeito.",
    c_greed_name: "Ganância Amaldiçoada",
    c_greed_desc: "Inimigos dropam 50% a menos de ouro.",
    c_weight_name: "Menos Peso",
    c_weight_desc: "Seu inventário foi reduzido em 2 slots.",
    c_tribute_name: "Tributo de Sangue",
    c_tribute_desc: "Perde 5 de vida ao coletar qualquer quantia de ouro.",
    compass_name: "Bússola",
    compass_desc: "Revela e guia até os inimigos.",
    map_name: "Mapa",
    map_desc: "Revela e guia até a saída.",
    enemy_count: "Inimigos:",
    antidote_name: "Antídoto",
    antidote_desc: "Cura veneno imediatamente.",
    poisoned: "ENVENENADO",
    cured: "CURADO DO VENENO!",
    poison_damage: "Veneno:",
    trap_spike: "ARMADILHA DE ESPINHOS!",
    trap_poison: "ARMADILHA DE VENENO!",
    trap_alarm: "ALARME! INIMIGO ATRAÍDO!",
    trap_explosive: "KABOOM! EXPLOSÃO!",
    trap_evaded: "Armadilha evitada (Velocidade)!",
    crow_reveal: "O Corvo avistou armadilhas!",
    paralyzed: "PARALISADO! Perdeu o turno!",
    egg_story: "O ovo se rompe sem som.\nA casca cai em pedaços negros, como carvão úmido.\nDe dentro, algo observa antes de respirar.\nUm corvo — pequeno, magro, atento demais para ser apenas um animal.\nEle não grasna. Não foge.\nApenas inclina a cabeça… como se já conhecesse você.\nA partir deste momento, o corvo caminha ao seu lado.\nEle não luta por você.\nEle não sangra por você.\nMas ele vê o que você não vê.\nOnde houver armadilhas ocultas, o corvo estará primeiro.\nOnde o chão mente, ele marcará o perigo com luz e presença.\nMesmo que você caia, mesmo que morra,\no corvo lembrará.\nE quando você retornar, ele já estará esperando.",
    egg_accept: "Aceitar o Destino"
  },
  EN: {
    inventory_title: "INVENTORY",
    inventory_full: "Inventory full!",
    use: "USE",
    store: "STORE",
    relic_choice: "CHOOSE A RELIC",
    relic_active: "ACTIVE RELIC",
    hero_placeholder: "HERO NAME",
    continue_journey: "Continue Journey",
    new_game: "New Game",
    start_journey: "Start Journey",
    feedback: "Feedback",
    abyss: "The Infinite Abyss",
    depth: "Depth",
    level: "Level",
    hp: "HP",
    armor: "ARMOR",
    atk: "ATK",
    vel: "SPD",
    diary: "Diary",
    view_diary: "View Diary",
    hide_diary: "Hide Diary",
    death_title: "DEATH",
    death_desc: "The Abyss claimed your soul.",
    rebirth: "Rebirth",
    victory: "Victory",
    collect_reward: "COLLECT REWARD",
    succumb: "SUCCUMB",
    chest_title: "Chest Blessing",
    merchant_title: "Wandering Merchant",
    altar_title: "Altar of Shadows",
    altar_inactive: "The Altar is silent. Kill an enemy first.",
    altar_prompt: "Pray at the Altar.",
    altar_button: "PRAY",
    close_deal: "Close Deal",
    bought_pet: "Pet bought!",
    bought_potion: "Potion bought!",
    bought_item: "Equipped!",
    tron_active: "GHOST HORSE ACTIVE!",
    language_br: "Portuguese",
    language_us: "English",
    language_es: "Spanish",
    theme_cave: 'Caves',
    theme_snow: 'Snowy Peaks',
    theme_desert: 'Dunes',
    theme_forest: 'Forest',
    theme_inferno: 'Inferno Zone',
    theme_ruins: 'Ancient Ruins',
    theme_void: 'Abyss',
    theme_mechanical: 'Mech Complex',
    theme_corrupted: 'Corrupted Zone',
    theme_catacombs: 'Catacombs',
    theme_ossuary: 'Ossuary',
    theme_astral: 'Astral Plane',
    theme_matrix: 'The Matrix',
    theme_furnace: 'Abyssal Furnace',
    theme_swamp: 'Toxic Swamp',
    theme_temple: 'Forgotten Temple',
    theme_chaos: 'Chaos Zone',
    theme_hive: 'Deep Hive',
    final_stats: "FINAL STATS",
    blood: "BLOOD",
    key: "KEY",
    combat_dealt: "dealt",
    combat_damage: "damage",
    combat_absorbed: "absorbed",
    combat_player: "You",
    combat_enemy: "Enemy",
    combat_pet: "Pet",
    pet_lobo: "WOLF",
    pet_puma: "PUMA",
    pet_corvo: "CROW",
    pet_cavalo: "HORSE",
    buy_horse: "RENT HORSE",
    descending: "Descending to level",
    log_entry: "entered the abyss.",
    log_depth: "Reached depth",
    log_key: "Key collected!",
    log_locked: "Locked! Need key and 1 kill!",
    log_trampled: "Trampled!",
    next: "NEXT",
    start: "START",
    tutorial_title: "WELCOME TO THE ABYSS",
    tutorial_guide_title: "Survival Guide:",
    tutorial_hp: "HEALTH",
    tutorial_hp_desc: "Keep above 0 or your run ends.",
    tutorial_atk: "ATTACK",
    tutorial_atk_desc: "Damage dealt per automatic hit.",
    tutorial_def: "SHIELD",
    tutorial_def_desc: "Protects HP and regenerates after fights.",
    tutorial_spd: "SPEED",
    tutorial_spd_desc: "Determines who strikes first.",
    tutorial_trial_title: "THE TRIAL",
    tutorial_trial_desc: "Stairs are sealed. Kill at least one enemy and find the key to advance.",
    tutorial_btn: "I AM READY",
    b_sharp_name: "Sharp Blood",
    b_sharp_desc: "+10% damage after first kill this floor.",
    b_fury_name: "Contained Fury",
    b_fury_desc: "+15% damage while below 50% HP.",
    b_strike_name: "Anxious Strike",
    b_strike_desc: "Your next attack deals double damage.",
    b_fists_name: "Consecrated Fists",
    b_fists_desc: "Attacks ignore half of enemy armor.",
    b_eyes_name: "Open Eyes",
    b_eyes_desc: "Key location revealed with glowing tracks.",
    b_luck_name: "Pilgrim Luck",
    b_luck_desc: "Extra chests may appear with 100 gold.",
    b_surrendered_name: "Surrendered Blood",
    b_surrendered_desc: "Heal 30% HP upon killing enemies.",
    b_accepted_name: "Accepted Offering",
    b_accepted_desc: "Next potion used this floor is not consumed.",
    b_greed_name: "Sacred Greed",
    b_greed_desc: "Enemies drop more gold this floor.",
    b_merchant_name: "Merchant's Blessing",
    b_merchant_desc: "Shop items cost 20% less this floor.",
    b_chest_name: "Consecrated Chest",
    b_chest_desc: "Next chest gives double bonuses.",
    c_fragile_name: "Fragile Blood",
    c_fragile_desc: "You take +10% damage from all sources.",
    c_hands_name: "Trembling Hands",
    c_hands_desc: "25% chance to miss attacks.",
    c_breath_name: "Short Breath",
    c_breath_desc: "You cannot attack in consecutive turns.",
    c_mark_name: "Mark of Prey",
    c_mark_desc: "Enemy attacks apply bleeding (-2 HP/turn).",
    c_reflexes_name: "Slow Reflexes",
    c_reflexes_desc: "Enemies always attack first.",
    c_darkness_name: "Ritual Darkness",
    c_darkness_desc: "Vision drastically reduced.",
    c_thirst_name: "Profane Thirst",
    c_thirst_desc: "Potions are 10% less effective.",
    c_denied_name: "Denied Offering",
    c_denied_desc: "Next potion used is wasted.",
    c_greed_name: "Cursed Greed",
    c_greed_desc: "Enemies drop 50% less gold.",
    c_weight_name: "Less Weight",
    c_weight_desc: "Inventory size reduced by 2.",
    c_tribute_name: "Blood Tribute",
    c_tribute_desc: "Lose 5 HP when picking up gold.",
    compass_name: "Compass",
    compass_desc: "Reveals and guides to enemies.",
    map_name: "Map",
    map_desc: "Reveals and guides to the exit.",
    enemy_count: "Enemies:",
    antidote_name: "Antidote",
    antidote_desc: "Cures poison immediately.",
    poisoned: "POISONED",
    cured: "POISON CURED!",
    poison_damage: "Poison:",
    trap_spike: "SPIKE TRAP!",
    trap_poison: "POISON TRAP!",
    trap_alarm: "ALARM! ENEMY ATTRACTED!",
    trap_explosive: "KABOOM! EXPLOSION!",
    trap_evaded: "Trap evaded (Speed)!",
    crow_reveal: "Crow revealed traps!",
    paralyzed: "PARALYZED! Turn lost!",
    egg_story: "The egg breaks without a sound.\nThe shell falls in black shards, like wet coal.\nFrom within, something watches before breathing.\nA crow — small, thin, too alert to be just an animal.\nIt does not caw. It does not flee.\nIt just tilts its head… as if it already knew you.\nFrom this moment on, the crow walks by your side.\nIt does not fight for you.\nIt does not bleed for you.\nBut it sees what you do not see.\nWhere there are hidden traps, the crow will be there first.\nWhere the ground lies, it will mark the danger with light and presence.\nEven if you fall, even if you die,\nthe crow will remember.\nAnd when you return, it will be waiting.",
    egg_accept: "Accept Destiny"
  },
  ES: {
    inventory_title: "INVENTARIO",
    inventory_full: "¡Inventario lleno!",
    use: "USAR",
    store: "GUARDAR",
    relic_choice: "ELIGE UNA RELIQUIA",
    relic_active: "RELIQUIA ACTIVA",
    hero_placeholder: "NOMBRE DEL HÉROE",
    continue_journey: "Continuar",
    new_game: "Nuevo Juego",
    start_journey: "Empezar",
    feedback: "Feedback",
    abyss: "El Abismo Infinito",
    depth: "Profundidad",
    level: "Nível",
    hp: "VIDA",
    armor: "ESCUDO",
    atk: "ATK",
    vel: "VEL",
    diary: "Diario",
    view_diary: "Ver Diario",
    hide_diary: "Ocultar Diario",
    death_title: "MUERTE",
    death_desc: "El abismo reclamó tu alma.",
    rebirth: "Renacer",
    victory: "Victoria",
    collect_reward: "RECOMPENSA",
    succumb: "SUCUMBIR",
    chest_title: "Bendición del Cofre",
    merchant_title: "Mercader Errante",
    altar_title: "Altar de Sombras",
    altar_inactive: "Altar silente. Mata 1 enemigo primero.",
    altar_prompt: "Ora en el Altar.",
    altar_button: "ORAR",
    close_deal: "Cerrar Trato",
    bought_pet: "Mascota comprada!",
    bought_potion: "Poción comprada!",
    bought_item: "Equipado!",
    tron_active: "¡CABALLO FANTASMA!",
    language_br: "Português",
    language_us: "Inglés",
    language_es: "Español",
    theme_cave: 'Cuevas',
    theme_snow: 'Picos Nevados',
    theme_desert: 'Dunas',
    theme_forest: 'Bosque',
    theme_inferno: 'Zona Infernal',
    theme_ruins: 'Ruínas',
    theme_void: 'Abismo',
    theme_mechanical: 'Mecánico',
    theme_corrupted: 'Corrupta',
    theme_catacombs: 'Catacumbas',
    theme_ossuary: 'Osario',
    theme_astral: 'Plano Astral',
    theme_matrix: 'Matrix',
    theme_furnace: 'Horno Abisal',
    theme_swamp: 'Pantano Tóxico',
    theme_temple: 'Templo Olvidado',
    theme_chaos: 'Zona del Caos',
    theme_hive: 'Colmena Profunda',
    final_stats: "ESTADÍSTICAS FINALES",
    blood: "SANGRE",
    key: "LLAVE",
    combat_dealt: "infligió",
    combat_damage: "daño",
    combat_absorbed: "absorvió",
    combat_player: "Tú",
    combat_enemy: "Enemigo",
    combat_pet: "Mascota",
    pet_lobo: "LOBO",
    pet_puma: "PUMA",
    pet_corvo: "CUERVO",
    pet_cavalo: "CABALLO",
    buy_horse: "ALQUILAR CABALLO",
    descending: "Bajando al nivel",
    log_entry: "entró en el abismo.",
    log_depth: "Llegó a la profundidad",
    log_key: "¡Llave recolectada!",
    log_locked: "¡Cerrado! ¡Mata 1 enemigo y busca la llave!",
    log_trampled: "¡Atropellado!",
    next: "SIGUIENTE",
    start: "EMPEGAR",
    tutorial_title: "BIENVENIDO AL ABISMO",
    tutorial_guide_title: "Guía de Supervivencia:",
    tutorial_hp: "VIDA",
    tutorial_hp_desc: "Mantén sobre 0 o tu partida termina.",
    tutorial_atk: "ATAQUE",
    tutorial_atk_desc: "Daño causado por golpe automático.",
    tutorial_def: "ESCUDO",
    tutorial_def_desc: "Protege tu vida y regenera tras peleas.",
    tutorial_spd: "VELOCIDAD",
    tutorial_spd_desc: "Define quién golpea primero.",
    tutorial_trial_title: "LA PRUEBA",
    tutorial_trial_desc: "Escaleras selladas. Mata al menos un enemigo y halla la llave para avanzar.",
    tutorial_btn: "ESTOY LISTO",
    b_sharp_name: "Sangre Afilada",
    b_sharp_desc: "+10% daño tras la primera muerte.",
    b_fury_name: "Furia Contenida",
    b_fury_desc: "+15% daño con menos de 50% HP.",
    b_strike_name: "Golpe Ansioso",
    b_strike_desc: "Próximo ataque inflige daño doble.",
    b_fists_name: "Puños Consagrados",
    b_fists_desc: "Ataques ignoran la mitad de la armadura.",
    b_eyes_name: "Ojos Abiertos",
    b_eyes_desc: "Ubicación de llave revelada con huellas.",
    b_luck_name: "Suerte Peregrina",
    b_luck_desc: "Cofres extra pueden aparecer con 100 de oro.",
    b_surrendered_name: "Sangre Rendida",
    b_surrendered_desc: "Sana 30% HP al matar enemigos.",
    b_accepted_name: "Ofrenda Aceptada",
    b_accepted_desc: "Próxima poción usada no se consume.",
    b_greed_name: "Codicia Sagrada",
    b_greed_desc: "Enemigos sueltan más oro.",
    b_merchant_name: "Bendición del Mercador",
    b_merchant_desc: "Objetos de la tienda cuestan 20% menos.",
    b_chest_name: "Cofre Consagrado",
    b_chest_desc: "Próximo cofre da bônus doble.",
    c_fragile_name: "Sangre Frágil",
    c_fragile_desc: "Recibes +10% daño de todas las fuentes.",
    c_hands_name: "Manos Temblorosas",
    c_hands_desc: "25% probabilidad de fallar ataques.",
    c_breath_name: "Aliento Corto",
    c_breath_desc: "No puedes atacar en turnos consecutivos.",
    c_mark_name: "Marca de Presa",
    c_mark_desc: "Ataques enemigos causan sangrado.",
    c_reflexes_name: "Reflejos Lentos",
    c_reflexes_desc: "Enemigos siempre atacan primero.",
    c_darkness_name: "Oscuridad Ritual",
    c_darkness_desc: "Visión drásticamente reducida.",
    c_thirst_name: "Sed Profana",
    c_thirst_desc: "Pociones son 10% menos efectivas.",
    c_denied_name: "Ofrenda Negada",
    c_denied_desc: "Próxima poción usada se desperdicia.",
    c_greed_name: "Codicia Maldita",
    c_greed_desc: "Enemigos sueltan 50% menos oro.",
    c_weight_name: "Menos Peso",
    c_weight_desc: "Inventario reducido en 2 slots.",
    c_tribute_name: "Tributo de Sangue",
    c_tribute_desc: "Pierdes 5 HP al recoger oro.",
    compass_name: "Brújula",
    compass_desc: "Revela y guía hacia los enemigos.",
    map_name: "Mapa",
    map_desc: "Revela y guía hacia la salida.",
    enemy_count: "Enemigos:",
    antidote_name: "Antídoto",
    antidote_desc: "Cura veneno inmediatamente.",
    poisoned: "ENVENENADO",
    cured: "¡VENENO CURADO!",
    poison_damage: "Veneno:",
    trap_spike: "¡TRAMPA DE PINCHOS!",
    trap_poison: "¡TRAMPA DE VENENO!",
    trap_alarm: "¡ALARMA! ¡ENEMIGO ATRAÍDO!",
    trap_explosive: "¡KABOOM! ¡EXPLOSIÓN!",
    trap_evaded: "¡Trampa evitada (Velocidad)!",
    crow_reveal: "¡El cuervo reveló trampas!",
    paralyzed: "¡PARALIZADO! ¡Turno perdido!",
    egg_story: "El huevo se rompe sin sonido.\nLa cáscara cae en pedazos negros, como carbón húmedo.\nDesde dentro, algo observa antes de respirar.\nUn cuervo — pequeño, delgado, demasiado atento para ser solo un animal.\nNo grazna. No huye.\nSolo inclina la cabeza... como si ya te conociera.\nA partir de este momento, el cuervo camina a tu lado.\nNo lucha por ti.\nNo sangra por ti.\nPero ve lo que tú no ves.\nDonde haya trampas ocultas, el cuervo estará primero.\nDonde el suelo miente, marcará el peligro con luz y presencia.\nIncluso si caes, incluso si mueres,\nel cuervo recordará.\nY cuando regreses, él ya estará esperando.",
    egg_accept: "Aceptar el Destino"
  }
};
